### ISSUE TITLE
Public -

### ISSUE THREAD

**Issue by ruchikav95** [sitthiph/CuddleBuddy#3]
1. HTML
2. CSS

**Comment by ruchikav95** [comment]
Currently working on HTML

**Comment by sitthiph** [comment]
Which HTML page are you currently working on?
How many pages is done?
What pages are done?

**Comment by ruchikav95** [comment]
> Which HTML page are you currently working on?
> How many pages is done?
> What pages are done?

Currently working on chat.html. 2 pages are done with the exception of the image upload section in signup.html and login popup window on index.html. Cuddlebuddy.html is WIP. Please refer to the remaining issues which include all details, moving parts and todos.
